name: Update Playlist

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests
      - name: Fetch API Key
        id: fetch_key
        run: |
          API_KEY=\$(curl -s "https://m.xigzo.store/apikey.json" | jq -r '.api_key')
          echo "API_KEY=\${API_KEY}" >> \$GITHUB_ENV
      - name: Run script
        run: python process.py
        env:
          YT_API_KEY: \${{ env.API_KEY }}
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add playlist.m3u
          git commit -m "🔄 Auto-updated playlist" || echo "No changes"
          git push
