name: Update Playlist

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Requests
        run: pip install requests

      - name: Run process.py
        run: python process.py

      - name: Commit and Push if Changed
        run: |
          git config --global user.name "sultanarabi161"
          git config --global user.email "sultanarabi161@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add playlist.m3u
            git commit -m "🔁 Auto-updated playlist.m3u"
            git push
          else
            echo "✅ No changes to commit"
