name: Update Playlist

on:
  schedule:
    - cron: '*/30 * * * *'  # Updates every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: python process.py
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add playlist.m3u
          git commit -m "🔄 Auto-updated playlist" || echo "No changes"
          git push
