name: Update Playlist

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install requests

      - name: Run process.py
        run: python process.py

      - name: Commit and Push
        run: |
          git config --global user.name "Sultan Bot"
          git config --global user.email "sultan@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "🔁 Auto-updated playlist.m3u"
          git push
